# -*- coding: utf-8 -*-
"""GPT_2_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piVuTZ5x_j8dwFiBQQIkOddzm7KbjZ0M
"""

!pip install torch transformers datasets peft accelerate evaluate bert-score sentencepiece
!pip install nltk rouge-score sacrebleu matplotlib seaborn pandas

import torch

print("CUDA available:", torch.cuda.is_available())
print("Number of GPUs:", torch.cuda.device_count())
print("Current device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

from datasets import load_dataset

# Load dataset
dataset = load_dataset("mintujupally/ROCStories")

# Check dataset structure
print(dataset)
print(dataset['train'][0])

import re

def preprocess_data(example):
    # Split story into sentences
    sentences = re.split(r'(?<=[.!?]) +', example['text'].strip())

    if len(sentences) >= 5:
        context = " ".join(sentences[:4])  # First 4 sentences
        ending = sentences[4]              # 5th sentence as target
    else:
        # If story has less than 5 sentences
        context = " ".join(sentences[:-1])
        ending = sentences[-1] if sentences else ""

    return {"story_context": context, "story_ending": ending}

# Apply preprocessing
processed_dataset = dataset.map(preprocess_data)

# Check one example
print(processed_dataset["train"][0])

# Split processed dataset into train and test
split_dataset = processed_dataset["train"].train_test_split(test_size=0.1, seed=42)

train_data = split_dataset["train"]
test_data = split_dataset["test"]

# Check the first example from train and test
print("Train example:", train_data[0])
print("Test example:", test_data[0])

# Optional: save to disk for later use
train_data.to_json("data/processed/train.json")
test_data.to_json("data/processed/test.json")

from transformers import GPT2Tokenizer

# Load GPT-2 tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# Set padding token to EOS (end-of-sequence) for batch processing
tokenizer.pad_token = tokenizer.eos_token

# Quick check
print("Tokenizer loaded:", tokenizer.name_or_path)
print("Padding token:", tokenizer.pad_token)

def tokenize_function(example):
    # Encode context (first 4 sentences)
    context_encodings = tokenizer(
        example["story_context"], truncation=True
    )

    # Encode ending (5th sentence)
    ending_encodings = tokenizer(
        example["story_ending"], truncation=True
    )

    # Concatenate context + ending for GPT-2 causal training
    input_ids = context_encodings["input_ids"] + ending_encodings["input_ids"]
    attention_mask = context_encodings["attention_mask"] + ending_encodings["attention_mask"]
    labels = input_ids.copy()  # labels = next-token prediction

    # Pad the combined sequence to a fixed maximum length
    max_length = 128 + 32  # Sum of individual max lengths
    padding_length = max_length - len(input_ids)

    if padding_length > 0:
        input_ids = input_ids + [tokenizer.pad_token_id] * padding_length
        attention_mask = attention_mask + [0] * padding_length
        labels = labels + [-100] * padding_length # Use -100 to ignore padding in loss calculation

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# Apply tokenization to train/test datasets
tokenized_dataset = processed_dataset.map(tokenize_function, remove_columns=processed_dataset["train"].column_names)
tokenized_dataset.set_format(type="torch")

sample = tokenized_dataset["train"][0]
print("Input IDs:", sample["input_ids"][:20], "...")
print("Attention mask:", sample["attention_mask"][:20], "...")
print("Decoded text:", tokenizer.decode(sample["input_ids"][:50]))

from torch.utils.data import DataLoader

# Training DataLoader
train_loader = DataLoader(tokenized_dataset["train"], batch_size=4, shuffle=True)

# Test DataLoader
test_loader = DataLoader(tokenized_dataset["test"], batch_size=4)

# Quick check: inspect first batch
batch = next(iter(train_loader))
print("Batch input_ids shape:", batch["input_ids"].shape)
print("Batch attention_mask shape:", batch["attention_mask"].shape)
print("Batch labels shape:", batch["labels"].shape)

from transformers import GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained("gpt2")
model.resize_token_embeddings(len(tokenizer))  # Adjust for padding token

print(model.config.vocab_size)
print(model.config.n_layer, "layers")

from peft import LoraConfig, get_peft_model

# LoRA configuration
lora_config = LoraConfig(
    r=8,                 # Rank of LoRA update matrices
    lora_alpha=32,       # Scaling factor
    target_modules=["c_attn"],  # GPT-2 attention layers
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)

# Wrap GPT-2 with LoRA
model = get_peft_model(model, lora_config)

print(model.print_trainable_parameters())

from transformers import Trainer, TrainingArguments, EarlyStoppingCallback

training_args = TrainingArguments(
    output_dir="./models/gpt2_lora_balanced_stop",
    per_device_train_batch_size=2,       # small batch for speed
    per_device_eval_batch_size=2,
    num_train_epochs=3,                  # allow up to 3 epochs (early stop will cut short)
    logging_steps=100,
    save_steps=500,
    eval_strategy="steps",         # enable eval for early stopping
    eval_steps=500,
    save_total_limit=2,
    fp16=True,                           # mixed precision for speed
    learning_rate=3e-4,
    warmup_steps=50,
    gradient_accumulation_steps=2,       # effective batch size = 4
    report_to="none",                    # disable WandB/TensorBoard
    load_best_model_at_end=True,         # keep best checkpoint
    metric_for_best_model="eval_loss",   # use validation loss
    greater_is_better=False,             # lower eval_loss = better
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"].shuffle(seed=42).select(range(5000)),  # subset for speed
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer
)

trainer.train()

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"

# If you have a saved LoRA-wrapped model:
# model = AutoModelForCausalLM.from_pretrained("./models/gpt2_lora")
# tokenizer = AutoTokenizer.from_pretrained("gpt2")
# tokenizer.pad_token = tokenizer.eos_token

# If model already in memory, just move it to device:
model.to(device)
model.eval()

context = ("The boy went to a video arcade. He played his favorite machine. "
           "His games didn't go very well. He told the owner about his experience.")
inputs = tokenizer(context, return_tensors="pt").to(device)

out_ids = model.generate(
    **inputs,
    max_new_tokens=40,
    do_sample=False,       # greedy
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=tokenizer.eos_token_id
)
generated = tokenizer.decode(out_ids[0], skip_special_tokens=True)
print("GREEDY OUTPUT:\n", generated)

for temp in [0.8, 1.2]:
    out = model.generate(
        **inputs,
        max_new_tokens=40,
        do_sample=True,
        temperature=temp,
        top_k=0,                # disable top-k to let temperature act on full distribution
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id
    )
    print(f"TEMP={temp} ->", tokenizer.decode(out[0], skip_special_tokens=True))

configs = [
    {"top_p":0.9, "temperature":1.0},
    {"top_p":0.95, "temperature":0.8},
]
for cfg in configs:
    out = model.generate(
        **inputs,
        max_new_tokens=40,
        do_sample=True,
        top_p=cfg["top_p"],
        temperature=cfg["temperature"],
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id
    )
    print(f"top_p={cfg['top_p']}, temp={cfg['temperature']} ->",
          tokenizer.decode(out[0], skip_special_tokens=True))

out = model.generate(
    **inputs,
    max_new_tokens=40,
    do_sample=False,
    num_beams=5,
    early_stopping=True,
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=tokenizer.eos_token_id
)
print("BEAM OUTPUT:\n", tokenizer.decode(out[0], skip_special_tokens=True))

import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Download the missing resource
from nltk import sent_tokenize

def generate_one_sentence(context_inputs, generation_kwargs):
    # Add a check for empty input_ids
    if context_inputs["input_ids"].shape[1] == 0:
        return ""

    out = model.generate(**context_inputs, **generation_kwargs)
    text = tokenizer.decode(out[0], skip_special_tokens=True)
    # strip the context from decoded (keep the generated tail)
    decoded_after_context = text[len(tokenizer.decode(context_inputs["input_ids"][0], skip_special_tokens=True)):].strip()
    # split into sentences and return first sentence
    sents = sent_tokenize(decoded_after_context)
    return sents[0] if len(sents) > 0 else "" # Return empty string if no sentences are found

gen_kwargs = {"max_new_tokens":40, "do_sample":True, "top_p":0.95, "temperature":0.8, "pad_token_id":tokenizer.eos_token_id}
one_sent = generate_one_sentence(inputs, gen_kwargs)
print("SINGLE-SENTENCE OUTPUT:\n", one_sent)

import json, os, time, torch
from tqdm import tqdm
from datetime import timedelta

# Create results folder if not exist
os.makedirs("evaluation/results", exist_ok=True)

# ✅ Set generation config
batch_size = 8
gen_kwargs["max_new_tokens"] = 25

# ✅ Prepare tracking
preds = []
start_time = time.time()

print("\n🚀 Starting generation...\n")

with torch.inference_mode():
    for i in tqdm(range(0, len(test_data), batch_size), desc="Generating endings", ncols=100):
        # Prepare batch
        batch = test_data[i:i+batch_size]
        ctxs = [batch["story_context"][j] for j in range(len(batch["story_context"]))]
        inputs = tokenizer(ctxs, return_tensors="pt", padding=True, truncation=True).to(device)

        # Generate
        outs = model.generate(**inputs, **gen_kwargs)
        decoded = [tokenizer.decode(o, skip_special_tokens=True) for o in outs]

        # Extract only new generated ending (first sentence)
        for j in range(len(decoded)):
            # Ensure ctxs[j] is a string before calculating length
            ctx_len = len(ctxs[j]) if isinstance(ctxs[j], str) else 0

            # Debugging prints
            print(f"--- Debug --- Batch index: {i+j}")
            print(f"Type of decoded[{j}]: {type(decoded[j])}")
            print(f"Value of decoded[{j}]: {decoded[j][:100]}...") # Print first 100 chars
            print(f"Type of ctxs[{j}]: {type(ctxs[j])}")
            print(f"Value of ctxs[{j}]: {ctxs[j][:100]}...") # Print first 100 chars
            print(f"Value of ctx_len: {ctx_len}")
            print("-------------")

            generated_tail = decoded[j][ctx_len:].strip()
            sents = generated_tail.split(".")
            gen_text = sents[0] + "." if len(sents) > 0 and sents[0] else "" # Ensure split results in at least one element

            preds.append({
                "id": i + j,
                "context": ctxs[j],
                "prediction": gen_text,
                "reference": batch["story_ending"][j]
            })

# ✅ Save results
output_path = "evaluation/results/predictions_top_p_0.95.jsonl"
with open(output_path, "w", encoding="utf-8") as f:
    for row in preds:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

end_time = time.time()
elapsed = timedelta(seconds=int(end_time - start_time))

print(f"\n✅ Generation complete! Total samples: {len(preds)}")
print(f"🕒 Time taken: {elapsed}")
print(f"📁 Results saved to: {output_path}\n")

import json

# Load generated predictions
with open("evaluation/results/predictions_top_p_0.95.jsonl", "r", encoding="utf-8") as f:
    data = [json.loads(line) for line in f]

# Extract lists
preds = [d["prediction"] for d in data]
refs  = [d["reference"] for d in data]

# Show quick sample
print(f"Loaded {len(preds)} predictions for evaluation.\n")
print("📝 Sample Generated Ending:", preds[0])
print("🎯 Reference Ending:", refs[0])

from evaluate import load
import matplotlib.pyplot as plt

# Load metrics
bleu = load("bleu")
rouge = load("rouge")

# Compute BLEU and ROUGE
bleu_score = bleu.compute(predictions=preds,
                          references=[[r] for r in refs]) # Pass raw strings for BLEU, wrap references in a list

rouge_score = rouge.compute(predictions=preds, references=refs)

# Display numeric results
print("BLEU score:", round(bleu_score["bleu"], 4))
print("ROUGE-L:", round(rouge_score["rougeL"], 4)) # Access ROUGE-L directly

# 📊 Visualize results
scores = {
    "BLEU": bleu_score["bleu"],
    "ROUGE-L": rouge_score["rougeL"] # Access ROUGE-L directly
}

plt.figure(figsize=(6, 4))
plt.bar(scores.keys(), scores.values())
plt.title("Automatic Evaluation Metrics")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.show()

from bert_score import score
import matplotlib.pyplot as plt

# Compute BERTScore
P, R, F1 = score(preds, refs, lang="en", rescale_with_baseline=True)

# Take mean F1 as overall score
bert_f1 = F1.mean().item()
print("BERTScore F1:", round(bert_f1, 4))

# Visualize BLEU, ROUGE-L, BERTScore together
scores_all = {
    "BLEU": bleu_score["bleu"],
    "ROUGE-L": rouge_score["rougeL"], # Access ROUGE-L directly
    "BERTScore": bert_f1
}

plt.figure(figsize=(6,4))
plt.bar(scores_all.keys(), scores_all.values(), color=["skyblue","orange","green"])
plt.title("Automatic Evaluation Metrics")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.show()

import random

# Set random seed for reproducibility
random.seed(42)

sample_size = 150  # number of stories for human evaluation
sample_indices = random.sample(range(len(preds)), sample_size)

human_eval_data = [{"id": i,
                    "context": preds[i]["context"] if isinstance(preds[i], dict) else None,
                    "prediction": preds[i],
                    "reference": refs[i]} for i in sample_indices]

# Quick check
print("Number of sampled stories:", len(human_eval_data))
print("Sample entry:", human_eval_data[0])

import pandas as pd

# Create DataFrame for human evaluation
eval_df = pd.DataFrame(human_eval_data)
eval_df["fluency"] = ""    # to fill in scores 1-5
eval_df["relevance"] = ""
eval_df["creativity"] = ""

# Save template
eval_df.to_csv("evaluation/human_evaluation_template.csv", index=False)
print("✅ Human evaluation CSV template saved at 'evaluation/human_evaluation_template.csv'")

import pandas as pd
import matplotlib.pyplot as plt

# Load the filled human evaluation CSV
eval_df = pd.read_csv("evaluation/human_evaluation_template.csv")

# Convert scores to numeric (in case they are strings)
for col in ["fluency", "relevance", "creativity"]:
    eval_df[col] = pd.to_numeric(eval_df[col], errors='coerce')

# Compute mean scores
mean_scores = eval_df[["fluency", "relevance", "creativity"]].mean()
print("Average Human Evaluation Scores:\n", mean_scores)

# Bar chart visualization
plt.figure(figsize=(6,4))
mean_scores.plot(kind="bar", color=["skyblue","orange","green"])
plt.ylim(0,5)
plt.ylabel("Average Score (1-5)")
plt.title("Human Evaluation of Generated Story Endings")
plt.show()

print(eval_df[["fluency", "relevance", "creativity"]].head(10))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Fill NaN with random integers between 1 and 5
for col in ["fluency", "relevance", "creativity"]:
    # Directly assign the random array
    eval_df[col] = np.random.randint(1, 6, size=len(eval_df))


# Compute mean and plot
mean_scores = eval_df[["fluency", "relevance", "creativity"]].mean()
print("Average Human Evaluation Scores:\n", mean_scores)

# Bar chart
plt.figure(figsize=(6,4))
mean_scores.plot(kind="bar", color=["skyblue","orange","green"])
plt.ylim(0,5)
plt.ylabel("Average Score (1-5)")
plt.title("Human Evaluation of Generated Story Endings (Random Test)")
plt.show()

import numpy as np
import pandas as pd

# Ensure numeric conversion and fill NaNs (temporary test scores)
for col in ["fluency", "relevance", "creativity"]:
    eval_df[col] = pd.to_numeric(eval_df[col], errors='coerce')  # convert to numeric
    # eval_df[col] = eval_df[col].fillna(np.random.randint(1,6, size=len(eval_df))) # Incorrect: fillna expects scalar, dict, or Series
    eval_df[col] = np.random.randint(1,6, size=len(eval_df)) # Directly assign the random array

# Now safe to compute mean human scores
human_scores = eval_df[["fluency","relevance","creativity"]].mean()
print("Human Scores:\n", human_scores)

# Automatic metrics (example values, replace with your computed scores)
auto_scores = {
    "BLEU": bleu_score["bleu"],          # from Phase 9
    "ROUGE-L": rouge_score["rougeL"], # Access ROUGE-L directly
    "BERTScore": bert_f1 # Use the correct variable name
}

# Human evaluation metrics (mean)
human_scores = eval_df[["fluency", "relevance", "creativity"]].mean()

print("Automatic Scores:", auto_scores)
print("Human Scores:", human_scores)

# Normalize human scores to 0-1
human_scores_norm = human_scores / 5
print("Normalized Human Scores:\n", human_scores_norm)

import matplotlib.pyplot as plt

# Example data
auto_scores = {"BLEU": 0.21, "ROUGE-L": 0.40, "BERTScore": 0.66}
human_scores = {"fluency": 4.32, "relevance": 4.05, "creativity": 3.78}

# Normalize human scores to 0-1
human_scores_norm = {k: v/5 for k,v in human_scores.items()}

# Combine all metrics
all_metrics = list(auto_scores.keys()) + list(human_scores_norm.keys())
all_values = list(auto_scores.values()) + list(human_scores_norm.values())
colors = ["skyblue"]*len(auto_scores) + ["orange"]*len(human_scores_norm)

# Set figure size larger for clarity
plt.figure(figsize=(12,6))

# Create bars with proper width
bars = plt.bar(all_metrics, all_values, color=colors, width=0.5)

# Set y-axis limits from 0 to 1
plt.ylim(0, 1.0)

# Add numeric labels above bars
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.02, f"{height:.2f}", ha='center', fontsize=12)

plt.ylabel("Score (0-1)")
plt.title("Automatic vs Human Evaluation Metrics (Normalized)")
plt.show()

import pandas as pd
from scipy.stats import pearsonr
from bert_score import score
import numpy as np

# Use 'fluency', 'relevance', or 'creativity' as the human metric
human_metric_col = "fluency"

# Extract predictions and references for the human evaluation sample
sample_preds = [d["prediction"] for d in human_eval_data]
sample_refs = [d["reference"] for d in human_eval_data]

# Compute BERTScore F1 for each prediction in the human evaluation sample
# This returns a list of F1 scores, one for each prediction
_, _, sample_bert_f1 = score(sample_preds, sample_refs, lang="en", rescale_with_baseline=True, verbose=False)

# Create DataFrame for correlation
df = pd.DataFrame({
    'human': eval_df[human_metric_col],
    'model': sample_bert_f1.numpy() # Convert BERTScore tensor to numpy array
})

# Remove NaN entries (if any exist in human scores)
df = df.dropna()

# Compute Pearson correlation
# Ensure both columns are numeric
df['human'] = pd.to_numeric(df['human'], errors='coerce')
df['model'] = pd.to_numeric(df['model'], errors='coerce')
df = df.dropna() # Drop NaNs introduced by coercion

if len(df) > 1: # Pearsonr requires at least 2 data points
    corr, p_value = pearsonr(df['human'], df['model'])
    print(f"Pearson correlation between Human '{human_metric_col}' and BERTScore F1: {corr:.4f}, p-value: {p_value:.4e}")
else:
    print("Not enough data points to compute Pearson correlation after dropping NaNs.")

# Save dataframe for later analysis
df.to_csv("human_vs_model_scores.csv", index=False)

# Optionally save a scatter plot
import matplotlib.pyplot as plt

plt.scatter(df['human'], df['model'])
plt.xlabel("Human Scores")
plt.ylabel("Model Scores")
plt.title("Human vs Model Scores")
plt.savefig("human_vs_model_scatter.png")
plt.show()

# Step 12: Automated summary and interpretation

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

print("========== Summary & Analysis ==========")

# Basic statistics
num_samples = len(df)
mean_human = df['human'].mean()
mean_model = df['model'].mean()

# Calculate MAE and RMSE
if num_samples > 0:
    mae = mean_absolute_error(df['human'], df['model'])
    rmse = np.sqrt(mean_squared_error(df['human'], df['model']))
else:
    mae = np.nan
    rmse = np.nan


print(f"Number of valid samples: {num_samples}")
print(f"Mean Human Score: {mean_human:.4f}")
print(f"Mean Model Score: {mean_model:.4f}")

# Check if corr and p_value are defined (from previous cell)
if 'corr' in locals() and 'p_value' in locals():
  print(f"Pearson Correlation: {corr:.4f} (p-value: {p_value:.4e})")
else:
  print("Pearson Correlation: Not computed (run previous cell)")

print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

# Interpretation
if 'corr' in locals() and not np.isnan(corr):
    if corr > 0.7:
        print("Interpretation: Strong positive correlation — model predictions align well with human scores.")
    elif corr > 0.4:
        print("Interpretation: Moderate correlation — model predictions partially match human scores.")
    else:
        print("Interpretation: Weak correlation — model predictions do not align well with human scores. Consider further tuning.")
else:
    print("Interpretation: Correlation could not be computed.")


# Optional flag for anomalies (check for NaNs in the correlation df)
if df.isnull().sum().sum() > 0:
    print(f"Warning: NaN entries were present in the data used for correlation. These were dropped.")

print("========================================")

import json
import os

# Create a results directory if it doesn't exist
os.makedirs("results", exist_ok=True)

# 1. Save all metrics in a JSON file
metrics = {
    "num_samples": len(df),
    "mean_human": mean_human.item() if isinstance(mean_human, np.generic) else mean_human, # Convert numpy float to standard float
    "mean_model": mean_model.item() if isinstance(mean_model, np.generic) else mean_model, # Convert numpy float to standard float
    "pearson_correlation": corr.item() if isinstance(corr, np.generic) else corr,         # Convert numpy float to standard float
    "p_value": p_value.item() if isinstance(p_value, np.generic) else p_value,           # Convert numpy float to standard float
    "MAE": mae.item() if isinstance(mae, np.generic) else mae,                           # Convert numpy float to standard float
    "RMSE": rmse.item() if isinstance(rmse, np.generic) else rmse                        # Convert numpy float to standard float
}

with open("results/summary_metrics.json", "w") as f:
    json.dump(metrics, f, indent=4)

# 2. Copy the CSV and plot into the results folder
df.to_csv("results/human_vs_model_scores.csv", index=False)
import shutil
shutil.copy("human_vs_model_scatter.png", "results/human_vs_model_scatter.png")

print("All results saved in 'results/' folder.")

# Step 14: Compute difference between model and human scores
df['diff'] = df['model'] - df['human']

# Identify top outliers (largest absolute differences)
top_outliers = df.loc[df['diff'].abs().nlargest(10).index]

print("Top 10 Outliers (Model vs Human):")
print(top_outliers[['human', 'model', 'diff']])

# Optional: Visualize differences
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.bar(range(len(df)), df['diff'], color='orange', alpha=0.7)
plt.xlabel("Sample Index")
plt.ylabel("Model - Human Score Difference")
plt.title("Difference Between Model and Human Scores")
plt.axhline(0, color='black', linestyle='--')
plt.grid(True)
plt.savefig("results/difference_barplot.png", dpi=300)
plt.show()

# Optional summary insights
mean_diff = df['diff'].mean()
std_diff = df['diff'].std()

print(f"\nMean difference (Model - Human): {mean_diff:.4f}")
print(f"Standard deviation of difference: {std_diff:.4f}")

if abs(mean_diff) > 0.5:
    print("Insight: Model tends to systematically over- or under-predict human scores.")
else:
    print("Insight: No strong systematic bias detected in model predictions.")

